# Reference: http://code.google.com/intl/fr-FR/appengine/docs/python/config/appconfig.html
application: cef-cross-site-navigation
version: 3beta
runtime: python27
threadsafe: false
api_version: 1

handlers:
# Page d accueil recherche.catholique.fr
- url: /
  script: recherche.index.app

# Responsive pages
- url: /nav/.*
  script: nav.index.app

# JS API
- url: /api/.*
  script: navigation_bar/1-0/navigation_bar.py

# New admin pages
- url: /admin2.*
  script: administration2.index.app
  login: required

# Old admin pages
- url: /admin.*
  script: administration.index.app
  login: required

# Static files
- url: /stylesheets
  static_dir: stylesheets

- url: /javascripts
  static_dir: javascripts

- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
